Add ios sample
KiiPlatform/thing-if-SDK-Doc pull request #4
Opened 2017-06-02 09:53 UTC by naoki-akimoto

iOSのサンプルアプリを追加しました。レビューをお願いします。

手元にてsnippet.shとbase.mdを使って各タグが問題ないことは確認しています。

2017-06-02 09:57 UTC, satoshikumano commented
@naoki-akimoto @yongpingchen スニペットの内容は任せます。

2017-06-02 09:58 UTC, satoshikumano approved these changes

2017-06-02 10:04 UTC, yongpingchen requested changes
@naoki-akimoto please add mark down template file.

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +        let owner = Owner(TypedID(.thing, id: "dummyID"), accessToken: "dummyToken")
`owner` should be in `variables`?

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +        // CodeTagStart: variables
tag name should be different with other platform, you can use like `variables_ios`

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +        // 1. Create ThingIFAPI
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +            // CodeTagStart: onboard
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +        // CodeTagStart: updateThingType
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +        // CodeTagStart: updateFirmwareVersion
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +        // CodeTagEnd: updateFirmwareVersion
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +            // CodeTagStart: postNewCommand
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +        // CodeTagStart: getCommand
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +            // CodeTagStart: postNewTrigger
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +            // CodeTagStart: patchTrigger
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +            // CodeTagStart: ungroupedQuery
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +            // CodeTagStart: groupedQuery
tag name should be different with other platforms

2017-06-02 10:08 UTC, yongpingchen commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +            // CodeTagStart: aggregate
tag name should be different with other platforms

2017-06-02 10:18 UTC, naoki-akimoto commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +        let owner = Owner(TypedID(.thing, id: "dummyID"), accessToken: "dummyToken")
In this sample, no values are in `variables`
If I insert `owner`, it's `thingIFAPI(_ios)` like this,
```
let app=**
let owner=**
let api=ThingIFAPI(app, owner: owner)
```

2017-06-02 10:27 UTC, naoki-akimoto commented on snippets/ios/SampleProject/SampleProject/ViewController.swift
> +        let owner = Owner(TypedID(.thing, id: "dummyID"), accessToken: "dummyToken")
reference: http://docs.kii.com/en/guides/thingifsdk/ios/initialize/

2017-06-02 10:45 UTC, naoki-akimoto commented
@yongpingchen fixed. Please confirm.

2017-06-05 02:23 UTC, yongpingchen approved these changes

2017-06-05 02:23 UTC, merged